baseURL = "https://www.cesarsaez.me/"

theme = "LoveIt"
themesDir = "themes/LoveIt"

title = "Cesar Saez"

defaultContentLanguage = "en"
languageCode = "en"
languageName = "English"
hasCJKLanguage = false

paginate = 12

enableGitInfo = true
enableRobotsTXT = true
enableEmoji = true

[author]
  name = "Cesar Saez"
  email = "hi@cesarsaez.me"
  link = "https://www.cesarsaez.me"

[menu]
  [[menu.main]]
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

[params]
  defaultTheme = "dark"
  gitRepo = "https://github.com/csaez/csaez.github.io"
  fingerprint = ""
  # date format
  dateFormat = "02-01-2006"
  title = "Cesar Saez"
  description = "Cesar's website"
  images = [""]

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"

    [params.header.title]
      logo = ""
      name = "Cesar Saez"
      pre = ""
      post = ""
      typeit = false

  [params.footer]
    enable = true
    custom = ""
    hugo = true
    copyright = true
    author = true
    since = 2012
    icp = ""
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.section]
    paginate = 20
    dateFormat = "02-01"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "02-01"
    rss = 10

  [params.app]
    title = "Cesar Saez"

  [params.search]
    enable = true
    type = "lunr"

  [params.home]
    rss = 10

    [params.home.profile]
      enable = true
      avatarURL = "/images/avatar.jpg"
      title = "Cesar Saez"
      subtitle = "Hi there, I'm a software engineer working on tech for the VFX industry. I'm currently leading the AI Research team at Foundry (based in the UK)."
      typeit = true
      social = true

    [params.home.posts]
      enable = true
      paginate = 6

  [params.social]
    GitHub = "csaez"
    Linkedin = "cesarsaez"
    Youtubechannel = "UCRjk6bi_1ZQ9sL69agz0xMg"
    Email = "hi@cesarsaez.me"
    RSS = true

    [params.social.Mastodon]
        weight = 0
        id = "@cesarsaez"
        prefix = "https://hachyderm.io"
        tittle = "Mastodon"

 [params.page]
    twemoji = true

    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true

    [params.page.code]
      copy = true
      maxShownLines = 50

    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = true
      Reddit = true
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = true
      Flipboard = false
      Weibo = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false

    [params.page.comment]
      enable = true
      
      [params.page.comment.utterances]
        enable = true
        repo = "csaez/utterances-repo"
        issueTerm = "pathname"
        label = "comments"
        lightTheme = "github-light"
        darkTheme = "github-dark"

  [params.typeit]
    speed = 100
    cursorSpeed = 1000
    cursorChar = "|"
    duration = -1

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[privacy]
  [privacy.twitter]
    enableDNT = true

  [privacy.youtube]
    privacyEnhanced = true

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]