baseURL = 'https://cesarsaez.me/'
languageCode = 'en-us'
title = 'Cesar Saez'
theme = "LoveIt"
defaultTheme = "dark"
gitRepo = "https://github.com/csaez/csaez.github.io"
enableEmoji = true

[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  version = "0.2.X"
  dateFormat = "02-01-2006"

[params.search]
  enable = true
  type = "lunr"

[params.home]
    rss = 10
    [params.home.profile]
      enable = true
      avatarURL = "/images/avatar.jpg"
      title = "Cesar Saez"
      subtitle = "Hi there, I'm a software engineer working on tech for the VFX industry, currently working as Lead Research Engineer, AI at Foundry (based in the UK)."
      typeit = false
      social = true

 [params.page]
    twemoji = true
    [params.page.toc]
      auto = false

[params.section]
    dateFormat = "02-01"

[params.social]
    Mastodon = "@cesarsaez@hachyderm.io"
    GitHub = "csaez"
    Linkedin = "cesarsaez"
    Youtubechannel = "UCRjk6bi_1ZQ9sL69agz0xMg"
    Email = "hi@cesarsaez.me"
    RSS = true

[author]
  name = "Cesar Saez"
  email = "hi@cesarsaez.me"
  link = ""

[menu]
  [[menu.main]]
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
